Real-Estate-Project/Real_Estate/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', include('listing.urls')),
    path('registration/', include('registration.urls')),
    path('contact/', include('contact.urls')),
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Real-Estate-Project/contact/urls.py
from django.urls import path
from .views import ContactView


app_name = "contactapp"

urlpatterns = [


    path('', ContactView.as_view(), name='contact'),



]

Real-Estate-Project/listing/urls.py
from django.urls import path
from .views import  AboutView, HomeView ,  PropertyListView, PropertyDetailView , PropertyCreateView, add_listing



app_name = "listing"


urlpatterns = [

    # path('', views.Home, name='home'),
    path('', HomeView.as_view(), name='home'),
    path('listings/', PropertyListView.as_view(), name='listings'),
    path('listing/<int:id>/', PropertyDetailView.as_view(), name='listing-detail'),
    path('about/', AboutView.as_view(), name='about'),
    path('add-listing/', add_listing, name='add-listing'), 
]

Real-Estate-Project/search/urls.py
from django.urls import path
from .views import SearchView



app_name = "searchapp"


urlpatterns = [

    path('', SearchView.as_view(), name='search'),



]

Real-Estate-Project/contact/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.



class Contact(models.Model):
    
    listing = models.CharField(max_length=200)
    listing_id = models.IntegerField()
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    message = models.TextField(blank=True)
    contact_date = models.DateTimeField(auto_now_add=True)
    user_id = models.IntegerField(blank=True)

    class SiteConfigurationConfig:
        default_auto_field = 'django.db.models.AutoField'
    
    def __str__(self):
        return self.name

Real-Estate-Project/listing/models.py
from django.db import models
from django.urls import reverse
from solo.models import SingletonModel


# Create your models here.
class Realtor(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos/realtor/%Y-%m-%d/')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    hire_date = models.DateTimeField(auto_now_add=True, blank=True)
  
    class SiteConfigurationConfig:
        default_auto_field = 'django.db.models.AutoField'

    class Meta:
        verbose_name = "Realtor"
        verbose_name_plural = "Realtors"

    def __str__(self):
        return self.name

class MVP(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)    

    class Meta:
        verbose_name = "MVP"
        verbose_name_plural = "MVP"

    def __str__(self):
        return self.realtor.name 

    

class Property(models.Model):

    realtor = models.ForeignKey(Realtor, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.IntegerField()
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=1)
    thumb_nail = models.ImageField(upload_to='photos/listings/%Y-%m-%d/')
    photo_1 = models.ImageField(upload_to='photos/listings/%Y-%m-%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/listings/%Y-%m-%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/listings/%Y-%m-%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/listings/%Y-%m-%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/listings/%Y-%m-%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/listings/%Y-%m-%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("listing:listing-detail", kwargs={"id": self.id})

Real-Estate-Project/search/models.py
from django.db import models

# Create your models here.

Real-Estate-Project/listing/forms.py
# Assuming this is in forms.py or a file where your forms are defined
from django import forms
from .models import Property

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = '__all__'  # You can also specify the fields explicitly if needed

   
    widgets = {
        'description': forms.Textarea(attrs={'rows': 5, 'cols': 40}),
    }

Real-Estate-Project/contact/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages

from .models import Contact

class ContactView(View):

    def get(self,request, *args, **kwargs):
        return redirect('/')


    def post(self, request, *args, **kwargs):
        if self.request.method == 'POST':
            listing_id = request.POST['listing_id']
            listing = request.POST['listing']
            name = request.POST['name']
            email = request.POST['email']
            phone = request.POST['phone']
            message = request.POST['message']
            user_id = request.POST['user_id']

      
            if self.request.user.is_authenticated:
                user_id = request.user.id
                has_contacted = Contact.objects.filter(listing_id=listing_id, user_id=user_id)
            if has_contacted:
                messages.error(request, 'You have already made an inquiry for this listing')
                return redirect('/listing/'+listing_id)

            contact = Contact(listing=listing, listing_id=listing_id, name=name, email=email, phone=phone, message=message, user_id=user_id )

            contact.save()

            messages.success(request, 'Your request has been submitted, a realtor will get back to you soon')
            return redirect('/listing/'+listing_id)

Real-Estate-Project/listing/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from contact.views import ContactView
from django.views.generic import CreateView , DetailView, ListView  , TemplateView 
from django.shortcuts import render, redirect
from .forms import PropertyForm
from .models import Property
from .forms import PropertyForm 

from .models import *

class HomeView(ListView):
    model = Property
    template_name = 'site/index.html'
    context_object_name = 'listings'

    def get_queryset(self):
        return self.model.objects.order_by('-list_date').filter(is_published=True)[:3]

class PropertyListView(ListView):
    model = Property
    template_name= 'site/listings.html'
    context_object_name = 'listings'
    paginate_by = 10

class PropertyDetailView(DetailView):
    model = Property
    template_name = 'site/listing.html'
    context_object_name = 'property'
    pk_url_kwarg = 'id'


class AboutView(TemplateView):
    template_name = 'site/about.html'

    def get_context_data(self, **kwargs):
         context = super(AboutView, self).get_context_data(**kwargs)
         context['realtors'] = Realtor.objects.all()
         context['MVP'] = MVP.objects.last()
         return context

    

class PropertyCreateView(CreateView):
    model = Property
    form_class = PropertyForm
    template_name = 'site/listing_form.html'  # Replace with your form template
    success_url = reverse_lazy('listing:listings')  # Redirect to listings after successful form submission

    def form_valid(self, form):
        # Set the user as the realtor when creating a new listing
        form.instance.realtor = self.request.user.realtor
        return super().form_valid(form)
    
from django.shortcuts import render, redirect
from .forms import PropertyForm

def add_listing(request):
    if request.method == 'POST':
        form = PropertyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_url')  # Redirect to a success URL
    else:
        form = PropertyForm()

    # Render the form without error messages
    return render(request, 'site/listing_form.html', {'form': form})



def add_contact(request):
    if request.method == 'POST':
        form = ContactView(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_url')  # Redirect to a success URL
    else:
        form = PropertyForm()

    return render(request, 'site/listing_form.html', {'form': form})

    

Real-Estate-Project/search/views.py
from django.views.generic import ListView
from listing.models import Property
# Create your views here.



class SearchView(ListView):
    model = Property 
    template_name = "site/search.html"
    context_object_name = 'listings'
    paginate_by = 20
    
    def get_queryset(self):
        # Start with an empty queryset
        queryset = Property.objects.all()

        # Keywords
        keywords = self.request.GET.get('keywords', '')
        if keywords:
            queryset = queryset.filter(description__icontains=keywords)

        # City
        city = self.request.GET.get('city', '')
        if city:
            queryset = queryset.filter(city__iexact=city)

        # State
        state = self.request.GET.get('state', '')
        if state:
            queryset = queryset.filter(state__iexact=state)

        # Bedrooms
        bedrooms = self.request.GET.get('bedrooms', '')
        if bedrooms:
            queryset = queryset.filter(bedrooms__iexact=bedrooms)

        # Price
        price = self.request.GET.get('price', '')
        if price:
            queryset = queryset.filter(price__lte=price)

        return queryset

Real-Estate-Project/templates/site/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About Us | {% endblock %}
{% block content %}

    <section id="showcase-inner" class="py-5 text-light">
        <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
            <h1 class="display-4">About RealEstateSite</h1>
            <p class="lead">At RealEstateSite, we're not just in the business of buying and selling properties; we're in the business of helping individuals and families find their dream homes. Our passion for real estate goes beyond transactions — it's about creating lasting connections and building communities.</p>
            </div>
        </div>
        </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'listing:home' %}">
                <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active"> About</li>
            </ol>
        </nav>
        </div>
    </section>

    <section id="about" class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <h2>We Search For The Perfect Home</h2>
                    <p class="lead">We have identified some of the best properties for you</p>
                    <img src="{% static 'img/about.jpg' %}" alt="">
                    <p class="mt-4">
                        <strong>Why Choose Us:</strong>
                        <br>
                        <br>
                        <strong>Expertise:</strong> With years of experience in the real estate market, our team of dedicated professionals possesses unparalleled expertise. We understand the nuances of the market, providing you with insightful guidance at every step.
                        <br>
                        <br>
                        <strong>Personalized Service:</strong> Your journey with us is unique, and we treat it as such. Our personalized service ensures that your specific needs and preferences are met, making the buying or selling process a seamless and enjoyable experience.
                        <br>
                        <br>
                        <strong>Community Focus:</strong> We believe in the power of community. Our commitment extends beyond real estate transactions to actively contributing to the growth and well-being of the neighborhoods we serve.
                        <br>
                        <br>
                        <strong>Innovation:</strong> Embracing technological advancements, we leverage the latest tools and platforms to streamline processes and enhance communication, providing you with a modern and efficient real estate experience.
                    </p>
                </div>
            </div>
            
        </div>
    </section>

   <!-- Work -->
<section id="work" class="bg-dark text-white text-center py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="display-4">Discover Your Dream Home</h2>
                <h4>Explore our curated selection of exceptional properties. Your dream home is just a click away!</h4>
                <hr>
                <a href="{% url 'listing:listings' %}" class="btn btn-secondary text-white btn-lg">View Our Featured Listings</a>
            </div>
        </div>
    </div>
</section>


    <!-- Team -->
    <section id="team" class="py-5">
        <div class="container">
        <h2 class="text-center">Our Team</h2>
        <div class="row text-center">

            {% for team in realtors %}
                <div class="col-md-4">
                <img src="{{ team.photo.url }}" alt="" class="rounded-circle mb-3">
                <h4>{{ team.name }}</h4>
                <p class="text-success">
                    <i class="fas fa-award text-success mb-3"></i> Realtor</p>
                <hr>
                <p>
                    <i class="fas fa-phone"></i> {{ team.phone }}</p>
                <p>
                    <i class="fas fa-envelope-open"></i> {{ team.email }}</p>
                </div>
            {% endfor %}

        </div>
        </div>
    </section>

{% endblock %}

Real-Estate-Project/templates/site/contact_form.html
<!-- portfolio/templates/portfolio/project_form.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Add a new project</h2>
  <form method="post" action="{% url 'listing:add_contact' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

Real-Estate-Project/templates/site/listing.html
{% extends 'base.html' %}

{% block content %}

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'listing:home' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listing:listings' %}">Listings</a>
          </li>
          <li class="breadcrumb-item active">{{ property.title }}</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <a href="{% url 'listing:listings' %}" class="btn btn-light mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{ property.thumb_nail.url }}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">
            {% if property.photo_1 %}
            <div class="col-md-2">
              <a href="{{ property.photo_1.url }}" data-lightbox="home-images">
                <img src="{{ property.photo_1.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if property.photo_2 %}
            <div class="col-md-2">
              <a href="{{ property.photo_2.url }}" data-lightbox="home-images">
                <img src="{{ property.photo_2.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if property.photo_3 %}
            <div class="col-md-2">
              <a href="{{ property.photo_3.url }}" data-lightbox="home-images">
                <img src="{{ property.photo_3.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if property.photo_4 %}
            <div class="col-md-2">
              <a href="{{ property.photo_4.url }}" data-lightbox="home-images">
                <img src="{{ property.photo_4.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if property.photo_5 %}
            <div class="col-md-2">
              <a href="{{ property.photo_5.url }}" data-lightbox="home-images">
                <img src="{{ property.photo_5.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if property.photo_6 %}
            <div class="col-md-2">
              <a href="{{ property.photo_6.url }}" data-lightbox="home-images">
                <img src="{{ property.photo_6.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}

          </div>
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">${{ property.price }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">{{ property.bedrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">{{ property.bathrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-car"></i> Garage:
                  <span class="float-right">{{ property.garage }}
                  </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">{{ property.sqft }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Lot Size:
                  <span class="float-right">{{ property.lot_size }} Acres
                  </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">{{ property.list_date }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">{{ property.realtor }}
                  </span>
                </li>


              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
              {{ property.description }}
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{ property.realtor.photo.url }}" alt="Seller of the month">
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">Prabhakar Y</h6>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>

  
{% endblock %}

Real-Estate-Project/templates/site/listing_form.html
{% extends 'base.html' %}
{% block title %} Add Listing | {% endblock %}
{% block content %}

<section id="add-listing" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4>
              <i class="fas fa-home"></i> Add Listing</h4>
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'listing:add-listing' %}" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                  <div class="form-group">
                      {{ field.label_tag }}
                      {{ field }}
                      {% if field.errors %}
                          {% for error in field.errors %}
                              <div class="text-danger">{{ error }}</div>
                          {% endfor %}
                      {% endif %}
                  </div>
              {% endfor %}
              <input type="submit" value="Add Listing" class="btn btn-secondary btn-block">
          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Real-Estate-Project/templates/site/search.html
{% extends 'base.html' %}
{% block content %}
<section id="showcase-inner" class="showcase-search text-white py-5">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <form method="GET" action="{% url 'searchapp:search' %}">
          <!-- Form Row 1 -->
          <div class="form-row">
            <div class="col-md-4 mb-3">
              <label class="sr-only">Keywords</label>
              <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)">
            </div>

            <div class="col-md-4 mb-3">
              <label class="sr-only">City</label>
              <input type="text" name="city" class="form-control" placeholder="City">
            </div>

            <div class="col-md-4 mb-3">
              <label class="sr-only">State</label>
              <select name="state" class="form-control">
                <option selected="true" disabled="disabled">State (All)</option>
                <option value="AL">Alabama</option>
                <option value="AK">Alaska</option>
                <option value="AZ">Arizona</option>
                <option value="AR">Arkansas</option>
                <option value="CA">California</option>
                <option value="CO">Colorado</option>
                <option value="CT">Connecticut</option>
                <option value="DE">Delaware</option>
                <option value="DC">District Of Columbia</option>
                <option value="FL">Florida</option>
                <option value="GA">Georgia</option>
                <option value="HI">Hawaii</option>
                <option value="ID">Idaho</option>
                <option value="IL">Illinois</option>
                <option value="IN">Indiana</option>
                <option value="IA">Iowa</option>
                <option value="KS">Kansas</option>
                <option value="KY">Kentucky</option>
                <option value="LA">Louisiana</option>
                <option value="ME">Maine</option>
                <option value="MD">Maryland</option>
                <option value="MA">Massachusetts</option>
                <option value="MI">Michigan</option>
                <option value="MN">Minnesota</option>
                <option value="MS">Mississippi</option>
                <option value="MO">Missouri</option>
                <option value="MT">Montana</option>
                <option value="NE">Nebraska</option>
                <option value="NV">Nevada</option>
                <option value="NH">New Hampshire</option>
                <option value="NJ">New Jersey</option>
                <option value="NM">New Mexico</option>
                <option value="NY">New York</option>
                <option value="NC">North Carolina</option>
                <option value="ND">North Dakota</option>
                <option value="OH">Ohio</option>
                <option value="OK">Oklahoma</option>
                <option value="OR">Oregon</option>
                <option value="PA">Pennsylvania</option>
                <option value="RI">Rhode Island</option>
                <option value="SC">South Carolina</option>
                <option value="SD">South Dakota</option>
                <option value="TN">Tennessee</option>
                <option value="TX">Texas</option>
                <option value="UT">Utah</option>
                <option value="VT">Vermont</option>
                <option value="VA">Virginia</option>
                <option value="WA">Washington</option>
                <option value="WV">West Virginia</option>
                <option value="WI">Wisconsin</option>
                <option value="WY">Wyoming</option>
              </select>
            </div>
          </div>
          <!-- Form Row 2 -->
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label class="sr-only">Bedrooms</label>
              <select name="bedrooms" class="form-control">
                <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
              </select>
            </div>
            <div class="col-md-6 mb-3">
              <select name="price" class="form-control">
                <option selected="true" disabled="disabled">Max Price (All)</option>
                <option value="100000">$100,000</option>
                <option value="200000">$200,000</option>
                <option value="300000">$300,000</option>
                <option value="400000">$400,000</option>
                <option value="500000">$500,000</option>
                <option value="600000">$600,000</option>
                <option value="700000">$700,000</option>
                <option value="800000">$800,000</option>
                <option value="900000">$900,000</option>
                <option value="1000000">$1M+</option>
              </select>
            </div>
          </div>
          <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
        </form>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'listing:home' %}">
            <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'listing:listings' %}">Browse Listings</a>
        </li>
        <li class="breadcrumb-item active"> Search Results</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
  <div class="container">
    <div class="row">

      <!-- Listing 1 -->
      {% for listing in listings %}
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="{{ listing.thumb_nail.url }}" alt="">
          <div class="card-img-overlay">
            <h2>
              <span class="badge badge-secondary text-white">${{ listing.price }}</span>
            </h2>
          </div>
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">{{ listing.title }} </h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }}  {{ listing.state }}, {{ listing.zipcode }}</p>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-th-large"></i> Sqft: {{ listing.sqft }} </div>
              <div class="col-6">
                <i class="fas fa-car"></i> Garage: {{ listing.garage }}</div>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
              <div class="col-6">
                <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
            </div>
            <hr>
            <div class="row py-2 text-secondary">
              <div class="col-12">
                <i class="fas fa-user"></i> {{ listing.realtor }}</div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-6">
                <i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
            </div>
            <hr>
            <a href="{{ listing.get_absolute_url }}" class="btn btn-primary btn-block">More Info</a>
          </div>
        </div>
      </div>

      {% endfor %}

    </div>
  </div>
</section>
{% endblock %}