Real-Estate-Project/Real_Estate/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', include('listing.urls')),
    path('registration/', include('registration.urls')),
    path('contact/', include('contact.urls')),
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Real-Estate-Project/listing/urls.py
from django.urls import path
from .views import  AboutView, HomeView ,  PropertyListView, PropertyDetailView , PropertyCreateView, add_listing



app_name = "listing"


urlpatterns = [

    # path('', views.Home, name='home'),
    path('', HomeView.as_view(), name='home'),
    path('listings/', PropertyListView.as_view(), name='listings'),
    path('listing/<int:id>/', PropertyDetailView.as_view(), name='listing-detail'),
    path('about/', AboutView.as_view(), name='about'),
    path('add-listing/', add_listing, name='add-listing'), 
]

Real-Estate-Project/registration/urls.py
from django.urls import include, path
from .views import RegisterView, LoginView, dashboard, LogoutView , DashBoardView


app_name = "registration"

urlpatterns = [


    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashBoardView.as_view(), name='dashboard'),
    
]

Real-Estate-Project/search/urls.py
from django.urls import path
from .views import SearchView



app_name = "searchapp"


urlpatterns = [

    path('', SearchView.as_view(), name='search'),



]

Real-Estate-Project/templates/includes/_footer.html
<!-- Footer -->
{% load solo_tags %}
{% get_solo 'SiteConfiguration.SiteConfiguration' as site_config %}
<footer class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> {{ site_config.site_name }}
</footer>

Real-Estate-Project/templates/includes/_head.html
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Font Awesome -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <!-- Custom -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- jQuery-->>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <!-- font awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-GLhlTQ8iK9tG3zZlRgcvP9H5LbVRVoFdUAd6aWF5Ll/6e5i+qBnyW/1RSJoP+2x" crossorigin="anonymous">

 

Real-Estate-Project/templates/includes/_header.html
  <!-- Top Bar -->
{% load solo_tags %}
{% get_solo 'SiteConfiguration.SiteConfiguration' as site_config %}

  <section id="top-bar" class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> {{ site_config.phone }}
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> {{ site_config.email }}
        </div>
      </div>
    </div>
  </section>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="index.html">
        <img src="" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li           
          {% if '/' == request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %} >
            <a class="nav-link" href="{% url 'listing:home' %}">Home</a>
          </li>
          <li           
          {% if 'about' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-item mr-3"
          {% endif %} >
            <a class="nav-link" href="{% url 'listing:about' %}">About</a>
          </li>
          <li 
          {% if 'listings' in request.path %}
              class="nav-item active mr-3"
          {% else %}
              class="nav-item mr-3"
          {% endif %} 
          >
            <a class="nav-link" href="{% url 'listing:listings' %}"> Property-List</a>
         </li>
        </li>
          <li 
          {% if 'add-listing' in request.path %}
              class="nav-item active mr-3"
          {% else %}
              class="nav-item mr-3"
          {% endif %} 
        >
          <a class="nav-link" href="{% url 'listing:add-listing' %}">Add Listing</a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li
            {% if 'dashboard' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
              <a class="nav-link" href="{% url 'registration:dashboard' %}">
               (User Dashboard {{ user.username }})</a>
            </li>
            <li class="nav-item mr-3">
              <a href="{% url 'registration:logout' %}" class="nav-link">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </li>
          {% else %}
            <li
            {% if 'register' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
            <a class="nav-link" href="{% url 'registration:register' %}">
              <i class="fas fa-user-plus"></i> Register</a>
            </li>
            <li
            {% if 'login' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >
            <a class="nav-link" href="{% url 'registration:login' %}">
              <i class="fas fa-sign-in-alt"></i>

                Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

Real-Estate-Project/templates/includes/_scripts.html
{% load static %}
<!-- Scripts -->
<script src="{% static 'js/main.js' %}"></script>